

mixed-port: 7779

allow-lan: true

bind-address: '0.0.0.0'


mode: rule


log-level: debug


dns:
  enable: false
  listen: 0.0.0.0:53
  ipv6: true # when the false, response to AAAA questions will be empty

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  # enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR

  nameserver:
    - 114.114.114.114 # default value
    - 8.8.8.8 # default value
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS
    - dhcp://en0 # dns from dhcp
    # - '8.8.8.8#en0'

proxies:
- name: "ss00"
  type: vless
  server: 127.0.0.1
  port: 443
  uuid: 795bdc6f-0b25-4dc4-b5eb-6615dbcd187e
  network: tcp
  tls: true
  udp: true
  flow: xtls-rprx-vision
  servername: www.amazon.com # REALITY servername
  reality-opts:
    public-key: ys9Xv94VKCv5fRIqrY_fK4TVL0TaNS9PpTeggLGigCI
    short-id: 906f47df46efecc5 # optional
  client-fingerprint: chrome # cannot be empty

proxy-groups:
- name: Proxy1
  type: url-test
  proxies:
  - 'ss00'
  url: https://www.baidu.com
  interval: 5

rules:
  # - DOMAIN-KEYWORD,tikvpn.com,DIRECT
  # - DOMAIN-KEYWORD,tikvpn.in,Proxy1
  # - DOMAIN-KEYWORD,ipinfo.io,DIRECT
  # - DOMAIN-KEYWORD,ipip.net,DIRECT
  - MATCH,Proxy1
